/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package daftarmahasiswa;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class Menu extends javax.swing.JFrame {

    private DefaultTableModel dtm;
    private Boolean isUpdate = false;
    private int selectedID = -1;
    private ArrayList<Mahasiswa> listMhs;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        listMhs = new ArrayList<>();
        //Dummy
        listMhs.add(new Mahasiswa("1111", "Aaaa", "A"));
        listMhs.add(new Mahasiswa("2222", "Bbbb", "B"));
        listMhs.add(new Mahasiswa("3333", "Cccc", "C"));
        // Set Table
        table_mahasiswa.setModel(setTable());
        // Hide Delete button
        btn_delete.setVisible(false);
    }

    public final DefaultTableModel setTable() {
        Object[] column = {"NIM", "Nama", "Nilai"};
        DefaultTableModel dataTabel = new DefaultTableModel(null, column);
        for (int i = 0; i < listMhs.size(); i++) {
            Object[] row = new Object[3];
            row[0] = listMhs.get(i).getNim();
            row[1] = listMhs.get(i).getNama();
            row[2] = listMhs.get(i).getNilai();

            dataTabel.addRow(row);
        }

        return dataTabel;
    }
    
    public void resetTextField() {
        //untuk mengosongkan textfield
        txtf_nim.setText("");
        txtf_nama.setText("");
        txtf_nilai.setText("");
    }

    public void insertData() {
        // Get Data
        String nim = txtf_nim.getText();
        String nama = txtf_nama.getText();
        String nilai = txtf_nilai.getText();
        
        if((nim.equals("")) || (nama.equals("")) || nilai.equals("")){
            JOptionPane.showMessageDialog(null, "Data tidak boleh ada yang kosong!");
        }else{
            listMhs.add(new Mahasiswa(nim, nama, nilai));
            //Update Table
            table_mahasiswa.setModel(setTable());
            
            resetTextField();
            System.out.println("Insert Success!");
            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan!");
        }
    }

    public void updateData() {
        // Get Data
        String nim = txtf_nim.getText();
        String nama = txtf_nama.getText();
        String nilai = txtf_nilai.getText();
        //System.out.println(nim + nama + nilai);

        listMhs.get(selectedID).setNim(nim);
        listMhs.get(selectedID).setNama(nama);
        listMhs.get(selectedID).setNilai(nilai);
        
        //Update Table
        table_mahasiswa.setModel(setTable());
        
        resetTextField();
        System.out.println("Update Success!");
        JOptionPane.showMessageDialog(null, "Data berhasil diubah!");
    }

    public void deleteData() {
        //buat array data mahasiswa (sementara)
        ArrayList<Mahasiswa> temp_listMhs = new ArrayList<>();
        
        for (int i = 0; i < listMhs.size(); i++) {
            if(selectedID != i){
                /* masukkan semua data ke array sementara 
                kecuali data pada baris yang akan di hapus */
                String nim = listMhs.get(i).getNim();
                String nama = listMhs.get(i).getNama();
                String nilai = listMhs.get(i).getNilai();
                temp_listMhs.add(new Mahasiswa(nim, nama, nilai));
            }
        }
        
        //masukkan array data mahasiswa baru
        listMhs = temp_listMhs;
        
        //Update Table
        table_mahasiswa.setModel(setTable());
        
        resetTextField();
        System.out.println("Delete Success!");
        JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_main = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        txtf_nim = new javax.swing.JTextField();
        lbl_nim = new javax.swing.JLabel();
        lbl_nama = new javax.swing.JLabel();
        txtf_nama = new javax.swing.JTextField();
        lbl_nilai = new javax.swing.JLabel();
        txtf_nilai = new javax.swing.JTextField();
        scrollpane_base = new javax.swing.JScrollPane();
        table_mahasiswa = new javax.swing.JTable();
        btn_delete = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_title.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbl_title.setText("Daftar Mahasiswa");

        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        txtf_nim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf_nimActionPerformed(evt);
            }
        });

        lbl_nim.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_nim.setText("NIM");

        lbl_nama.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_nama.setText("Nama");

        txtf_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf_namaActionPerformed(evt);
            }
        });

        lbl_nilai.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_nilai.setText("Nilai");

        txtf_nilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf_nilaiActionPerformed(evt);
            }
        });

        table_mahasiswa.setAutoCreateRowSorter(true);
        table_mahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_mahasiswa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        table_mahasiswa.setUpdateSelectionOnSort(false);
        table_mahasiswa.setVerifyInputWhenFocusTarget(false);
        table_mahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_mahasiswaMouseClicked(evt);
            }
        });
        scrollpane_base.setViewportView(table_mahasiswa);

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_mainLayout = new javax.swing.GroupLayout(panel_main);
        panel_main.setLayout(panel_mainLayout);
        panel_mainLayout.setHorizontalGroup(
            panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_mainLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_mainLayout.createSequentialGroup()
                        .addGroup(panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_title)
                            .addGroup(panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panel_mainLayout.createSequentialGroup()
                                    .addComponent(lbl_nama)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtf_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panel_mainLayout.createSequentialGroup()
                                    .addComponent(lbl_nim)
                                    .addGap(55, 55, 55)
                                    .addComponent(txtf_nim, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_mainLayout.createSequentialGroup()
                                    .addComponent(lbl_nilai)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtf_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_add)
                            .addComponent(btn_delete)
                            .addComponent(btn_cancel)))
                    .addComponent(scrollpane_base, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        panel_mainLayout.setVerticalGroup(
            panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_mainLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbl_title)
                .addGap(26, 26, 26)
                .addGroup(panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtf_nim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nim)
                    .addComponent(btn_add))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtf_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nama)
                    .addComponent(btn_cancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtf_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nilai)
                    .addComponent(btn_delete))
                .addGap(42, 42, 42)
                .addComponent(scrollpane_base, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtf_nimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf_nimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_nimActionPerformed

    private void txtf_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_namaActionPerformed

    private void txtf_nilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf_nilaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_nilaiActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        if (isUpdate == false)
            insertData();
        else {
            updateData();
            btn_add.setText("Add");
            btn_delete.setVisible(false);
            this.isUpdate = false;
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void table_mahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_mahasiswaMouseClicked
        // TODO add your handling code here:
        this.isUpdate = true;

        //Get Selected Data
        int row = table_mahasiswa.getSelectedRow();
        String selectedNim = (table_mahasiswa.getModel().getValueAt(row, 0).toString());
        String selectedNama = (table_mahasiswa.getModel().getValueAt(row, 1).toString());
        String selectedNilai = (table_mahasiswa.getModel().getValueAt(row, 2).toString());

        for (int i = 0; i < listMhs.size(); i++) {
            if (selectedNim.equals(listMhs.get(i).getNim())) {
                selectedID = i;
                break;
            }
        }

        //System.out.println(selectedID);
        txtf_nim.setText(selectedNim);
        txtf_nama.setText(selectedNama);
        txtf_nilai.setText(selectedNilai);

        btn_add.setText("Update");
        btn_delete.setVisible(true);
    }//GEN-LAST:event_table_mahasiswaMouseClicked

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        if (isUpdate == true) {
            deleteData();
            btn_add.setText("Add");
            btn_delete.setVisible(false);
            this.isUpdate = false;
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        btn_add.setText("Add");
        btn_delete.setVisible(false);
        this.isUpdate = false;
        resetTextField();
    }//GEN-LAST:event_btn_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_delete;
    private javax.swing.JLabel lbl_nama;
    private javax.swing.JLabel lbl_nilai;
    private javax.swing.JLabel lbl_nim;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JPanel panel_main;
    private javax.swing.JScrollPane scrollpane_base;
    private javax.swing.JTable table_mahasiswa;
    private javax.swing.JTextField txtf_nama;
    private javax.swing.JTextField txtf_nilai;
    private javax.swing.JTextField txtf_nim;
    // End of variables declaration//GEN-END:variables
}
